[package]
name = "project-euler"
version = "0.1.0"
authors = ["Rémi Dupré <r.dupre@qwant.com>"]
edition = "2018"

[dependencies]
cached = { version = "0.23.0", default_features = false, features = [ "proc_macro" ] }
colored = "2.0.0"
fxhash = "0.2.1"
num-bigint = "0.4.0"
