[package]
name = "round_1"
version = "0.1.0"
edition = "2018"

[dependencies]
testcase = { git = "https://github.com/remi-dupre/testcase-rs.git" }
testcase_derive = { git = "https://github.com/remi-dupre/testcase-rs.git" }
