[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Rémi Dupré <r.dupre@qwant.com>"]
edition = "2018"

[dependencies]
aoc = { git = "https://github.com/remi-dupre/aoc.git", branch = "main" }
itertools = "0.9.0"
bytecount = "0.6.2"
