[package]
name = "beatthehash"
version = "0.1.0"
edition = "2021"

[dependencies]
hamming = "0.1.3"
hex-literal = "0.4.1"
indicatif = "0.17.11"
skein = "0.1"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
